### ISSUE TITLE
Should query params take precedence over the POST payload?

### ISSUE THREAD

**Issue by devinus** [RebelMail/hapi-human-payload#1]
I think query params would be better viewed as default values to a POST endpoint.

``` http
POST /endpoint?foo=1 HTTP/1.1

foo=2
```

The value of `foo` should be `2`.

**Comment by motdotla** [comment]
I agree.

**Comment by motdotla** [comment]
Actually query params do win out currently?  https://github.com/RebelMail/hapi-human-payload/blob/master/test/index.js#L79

Did you mean POST params should win?

**Comment by elbuo8** [comment]
Post should win.

#mobilmail

On Thu, Feb 26, 2015 at 3:38 PM -0800, "Mot" notifications@github.com wrote:

Actually query params do win out currently?  https://github.com/RebelMail/hapi-human-payload/blob/master/test/index.js#L79

Did you mean POST params should win?

**Comment by motdotla** [comment]
Ok, I think @devinus meant POST too. I'm changing.

**Comment by motdotla** [comment]
Changed here: https://github.com/RebelMail/hapi-human-payload/commit/fba5d9ee7707a86af0022bdf93a21ed9cebce9d2

**Comment by devinus** [comment]
:+1: That's what I meant, yes.
